name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -c "Release" --self-contained false
    - name: Deploy
      uses: drud/action-cross-commit@master
      with:
        source-folder: bin/Release/net5.0/publish
        destination-repository: https://nebulatgs:${{ secrets.API_TOKEN_GITHUB }}@github.com/hexa-deploy
        destination-folder: ./publish
        destination-branch: main
        git-user: "Actions"
        git-user-email: infinitewormhole@gmail.com
        git-commit-message: "Automated Build"
        git-commit-sign-off: "false"
        excludes: README.md
#     - name: Deploy
#       run: |
#         git clone https://github.com/nebulatgs/hexa-deploy.git
#         cp bin/Release/net5.0/publish hexa-deploy -r
#         cd hexa-deploy
#         git add .
#         git commit -m "Automated Build"
#         git push
        
